Feature: search, spconfig, multi-environment support
sailpoint-oss/sailpoint-cli pull request #36
Opened 2023-02-09 02:51 UTC by luke-hagar-sp

## Description
What is the intent of this change and why is it being made?

Adds features:
Search
SP-Config
Multi-Env Support
Simplified config file structure

## How Has This Been Tested?
What testing have you done to verify this change?

2023-02-10 19:18 UTC, colin-mckibben-sp requested changes

2023-02-10 19:18 UTC, colin-mckibben-sp commented on cmd/root/root.go
> +var version = "0.4.2"
Give this a minor version bump (i.e. 0.5.0).

2023-02-23 20:03 UTC, philip-ellis-sp requested changes

2023-02-23 20:23 UTC, luke-hagar-sp commented on cmd/root/auth.go
> +		{Title: "OAuth", Description: "OAuth2.0 Authentication - Sign in via the Web Portal"},
Good Catch, I'm commenting out the OAuth option for now, but this is intended to handle no arg uses, and give them a menu to pick from. Additionally, as the pipeline method is determined by the env vars populated, that shouldn't be an option here. this is going to look silly until OAuth is implemented

2023-02-23 20:24 UTC, luke-hagar-sp commented on cmd/spconfig/status.go
> +			for i := 0; i < len(exportJobs); i++ {
The validation for all of this occurs in the `config.InitConfig()` usage above these lines, if you are missing variables you get a yellow warning telling you whats missing.

2023-02-23 20:25 UTC, luke-hagar-sp commented on cmd/transform/preview.go
> +			resp, err := Client.Get(cmd.Context(), util.ResourceUrl(endpoint, idProfile))
this was something we discussed previously, and I started doing that, but I believe there IS a beta endpoint that currently has a breaking bug, but will ultimately replace this call, Colin knows more about it

2023-02-23 20:27 UTC, luke-hagar-sp commented on cmd/va/troubleshoot.go
> +				orgErr := va.RunVACmdLive(endpoint, password, "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/luke-hagar-sp/VA-Scripts/main/stunt.sh)\"")
this command is not currently available for use, I intend on making a couple of changes, but this is the command that requires open sourcing that bash script written by support.

A notification or warning of sorts would be good though i agree, I also need to adjust the way the logs are collected

2023-02-23 20:28 UTC, luke-hagar-sp commented on cmd/va/update.go
> +				_, updateErr := va.RunVACmd(endpoint, password, "sudo update_engine_client -check_for_update")
thats a fantastic idea, I think hard coding the commands to variables and then referencing those variables would be acceptable. should I do that now? or note that for ANOTHER pr?

2023-02-23 20:29 UTC, luke-hagar-sp commented on internal/config/oauth.go
> +	tr := &http.Transport{
Agreed

2023-02-23 20:33 UTC, luke-hagar-sp commented on internal/search/search.go
> +	switch indicie {
I would like to chat about the way the SDK currently handles this, its a bit weird to me.

2023-02-23 20:53 UTC, philip-ellis-sp commented on cmd/va/update.go
> +				_, updateErr := va.RunVACmd(endpoint, password, "sudo update_engine_client -check_for_update")
lets create an issue for this so it isn't forgotten, so yes, another PR later :)

2023-02-23 20:54 UTC, luke-hagar-sp commented on internal/config/oauth.go
> +	tr := &http.Transport{
Done

2023-02-23 21:03 UTC, luke-hagar-sp commented on cmd/va/update.go
> +				_, updateErr := va.RunVACmd(endpoint, password, "sudo update_engine_client -check_for_update")
This is done

2023-02-23 21:04 UTC, luke-hagar-sp commented on cmd/root/auth.go
> +		{Title: "OAuth", Description: "OAuth2.0 Authentication - Sign in via the Web Portal"},
this is done

2023-02-27 16:08 UTC, philip-ellis-sp approved these changes

2023-02-27 16:10 UTC, merged